language: python
python:
  - "2.7"
install: "pip install -r requirements.txt --use-mirrors"
script: ./run_tests.sh

language: python
python:
  - "3.4"
install: "pip install -r requirements.txt --use-mirrors"
script: ./run_tests.sh
